[project]
name = "bind_ctypes"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["uv_build>=0.7.10,<0.8.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-include = ["src/bind_ctypes/*"]
